# Конфигурация USB Monitor Client

# Настройки сервера (только HTTPS для безопасности)
server:
  server_url: "https://192.168.1.100:443"  # HTTPS URL сервера администратора
  timeout: 10                               # Таймаут запросов в секундах
  retry_attempts: 3                         # Количество попыток подключения
  retry_delay: 5                            # Задержка между попытками в секундах
  cache_duration: 300                       # Время кэширования результатов в секундах (5 минут)
  
  # SSL настройки для самоподписанных сертификатов
  ssl_verify: false                         # false для самоподписанных сертификатов
  ssl_cert_path: ""                         # Путь к CA сертификату (если нужен)
  ssl_warnings: false                       # Отключить предупреждения SSL
